### ISSUE TITLE
vue3.0 cliError: Cannot find module 'vs/editor/contrib/anchorSelect/anchorSelect'

### ISSUE THREAD

**Issue by Uranus-s** [FE-Mars/monaco-editor-vue#32]
vue.config.js  Cannot run after adding code
```
const MonacoWebpackPlugin = require('monaco-editor-webpack-plugin')
 
module.exports = {
  chainWebpack: config => {
    config.plugin('monaco-editor').use(MonacoWebpackPlugin, [
      {
        // Languages are loaded on demand at runtime
        languages: ['json', 'javascript', 'html', 'xml']
      }
    ])
  }
}
```

**Comment by rahulkumarsingh73690** [comment]
Same issue in vue 3

**Comment by rahulkumarsingh73690** [comment]
> monaco-editor-webpack-plugin

Found solution 👍 

monaco-editor-webpack-plugin 1.9.0 is supported currently in this monaco-editor-vue

**Comment by yerol** [comment]
@rahulkumarsingh73690 thanks. It works with monaco-editor-webpack-plugin 1.9.1 as well 👍

**Comment by FE-Mars** [comment]
Thanks, I'll close the issue
